# Generated by Django 6.0 on 2026-03-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undernote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='url',
        ),
    ]
