# Generated by Django 6.0 on 2026-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('undernote', '0002_remove_audio_duration_remove_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='audio',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
