# Generated by Django 6.0 on 2026-03-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overnote', '0003_audio_duration_audio_url_alter_audio_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(default='my audio', max_length=120),
        ),
    ]
