# Generated by Django 6.0 on 2026-03-09 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overnote', '0006_cowriter_project_cowriters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='overnote.audio')),
            ],
        ),
    ]
