# Generated by Django 6.0 on 2026-03-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overnote', '0007_transcription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcription',
            old_name='created_at',
            new_name='transcribed_at',
        ),
    ]
