# Generated by Django 6.0 on 2026-03-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overnote', '0009_audio_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='owner',
            new_name='creator',
        ),
    ]
