# Generated by Django 6.0 on 2026-03-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overnote', '0010_rename_owner_audio_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.CharField(choices=[('type', 'Type'), ('section', 'Section')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='audio',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='audios', to='overnote.category'),
        ),
    ]
