# Generated by Django 6.0 on 2026-03-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overnote', '0011_category_audio_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songwriterprofile',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
